### ISSUE TITLE
Add google maps as a basemap

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#11]
Add google maps or google earth as the default basemap instead of Bing maps.

**Comment by marsxul** [comment]
only add google earth, but maintain the original gray as the default basemap

**Comment by 3vivekb** [comment]
I'm sorry @marsxul.  User testing showed they didn't like the grey basemap.  I think the plan should be we switch to google maps instead.  It looks better.

**Comment by marsxul** [comment]
perhaps we should create a custom google map, so it doesnt complete look like google.

**Comment by ghost** [comment]
I'd have the agree with the colorscale, its really difficult to make hide/tail of the individual routes. Would say that you're better off with ADA compatibility with a multi-color scheme.

**Comment by 3vivekb** [comment]
Development for this will be difficult.  We will push this to the rebuild.

**Comment by marsxul** [comment]
I would like the Google Maps basemap simple atlas to be the default basemap, google satellite hybrid to be an option as well, maybe leave the amigoGray as well.

**Comment by marsxul** [comment]
two options, one is to add google maps api via javascript in place of bing
the other option is to add google maps api via leaflet

https://developers.google.com/maps/documentation/javascript/tutorial
https://developers.google.com/maps/documentation/javascript/examples/map-simple
https://developers.google.com/maps/documentation/javascript/examples/maptype-base

http://stackoverflow.com/questions/33343881/leaflet-in-google-maps 
http://bl.ocks.org/crofty/2197701

**Comment by 3vivekb** [comment]
- [ ] Fix grey line problem
- [ ] Stops when you have route details up should be clickable
- [ ] Location button not filling in start address
