### ISSUE TITLE
Mobile Gmaps resizing issues

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#112]
- [x] In Android chrome the map doesn't resize after plotting a trip
- [ ] In iOS Safari the drawn map resizes in an odd way.

**Comment by 3vivekb** [comment]
- [x] On desktop zooming in and out causes the drawn map to be a little funky.

**Comment by linuxwebexpert** [comment]
Most likely an issue related to the way the base map object is built...
Investigating and starting new branch in order to rebuild core map layers

**Comment by linuxwebexpert** [comment]
Creating new issues for mobile devices and browsers as they vary by OS
