### ISSUE TITLE
Mobile Gmaps Map selection needs to be more mobile friendly

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#113]
Right now the map selection in mobile view for gmaps takes up too much of the screen.  We should shrink it down to what it was like in the amigocloud maps view.

**Comment by 3vivekb** [comment]
Remove "Aerial" and rename "Hybrid" to "Aerial"

**Comment by linuxwebexpert** [comment]
Fixed in branch gmaps_mobile-#113
Testing on devplanner.vta.org

**Comment by 3vivekb** [comment]
This issue passes!
