### ISSUE TITLE
Can't move map properly in Android

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#114]
You can't move the map properly in Android after a trip is plotted - it's very unresponsive.

**Comment by linuxwebexpert** [comment]
Resolved for Android 5.x and up...
https://www.browserstack.com/start#os=android&os_version=6.0&device=Motorola+Moto+X+2nd+Gen&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fdevplanner.vta.org%2Fplanner&speed=1

Won't fix for Android < 5 due to Leaflet master issues
