### ISSUE TITLE
 In iOS Safari the drawn map resizes in an odd way.

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#118]

**Comment by linuxwebexpert** [comment]
Fixed iOS maps in branches drag_maps-#114 and ios_maps-#118

**Comment by 3vivekb** [comment]
Still zooms weird.
![image uploaded from ios](https://user-images.githubusercontent.com/4524205/27346432-0e6ac842-55a2-11e7-96f2-fe98029e00b4.jpg)

**Comment by 3vivekb** [comment]
Weird zoom is cited in #126
