### ISSUE TITLE
When park and Ride is selected, some text is hidden

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#12]
When Park and Ride is selected, some text is hidden.
![screen shot 2016-08-09 at 11 45 59 am](https://cloud.githubusercontent.com/assets/4524205/17529133/f76058c4-5e26-11e6-8f7d-4ad4081253af.png)

**Comment by Kyle-Falconer** [comment]
Will be fixed in #28 with the redesign of the route-card-views.
