### ISSUE TITLE
Pinch and zoom on iOS draws funnily

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#126]
Pinch and zoom looks weird on iOS when you have a route displayed.

Maybe we should just hide the route during pinch and zoom and then redraw.

**Comment by 3vivekb** [comment]
Pinch and zoom also now fails on Android.

**Comment by linuxwebexpert** [comment]
Fixed -- https://scvta.slack.com/archives/G5DGN0X7A/p1498660714533293
