### ISSUE TITLE
Initial Bus Stop is not visible

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#127]
![bus_oval](https://user-images.githubusercontent.com/4524205/27409779-09fe7816-5698-11e7-980c-31d8fc38dda7.png)

If you plan a trip and select a different trip than the first one, the initial bus symbol disappears.

Also the first bus stop is not interactive.

**Comment by linuxwebexpert** [comment]
![Screenshot_2017-06-27_14-38-33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58ed1cc86ceb8a0020530be6/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1c36416713e7b539c7a24c8b070f2112843434d0eee1e020a17b8eb8339a3b16d758b0e03bbd2695e72c13817a4b8821ab854b2268f5d99a4fedb1294b7607caddecd5d340c061983fe593ca89c42c15df04fe04e54b65e.png)

Stop are visible now and popups working on desktop and mobile

Renaming current branch and creating PR for this issue...
Expected we can test this today on staging server
