### ISSUE TITLE
Buses aren't moving they are flickering

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#128]
When a bus is updated, they don't move across the screen, they flicker and reappear in a different place.  They should, at a medium pace, drag to the new location.

**Comment by 3vivekb** [comment]
This was fixed with https://github.com/vta/modeify/issues/114

**Comment by 3vivekb** [comment]
This is still broken for iOS phones.

**Comment by linuxwebexpert** [comment]
This has been broken since release 1.9 -- our current tripplanner.vta.org
Tested this morning with iPhone and Safari, same behavior...
Upgrading size of this task and recommending deferral to next sprint

**Comment by 3vivekb** [comment]
I think fixing the underlying issue has become too difficult, we should just turn off the bus refresh on iOS phones and the safari browser.

**Comment by linuxwebexpert** [comment]
When tested on iOS or Safari -- the vehicle markers refresh have been disabled
Still refreshes real-time markers on Chrome all platforms
Please confirm using BrowserStack and test suite matrix

**Comment by marsxul** [comment]
flickering seems to be gone, just curious how frequent do the vehicles update their location, it seems rather latent. IS it every 10 seconds or so?
