### ISSUE TITLE
Failed to parse source map

### ISSUE THREAD

**Issue by linuxwebexpert** [vta/modeify#138]
When I inspect I see this - DevTools failed to parse SourceMap: https://tripplanner.vta.org/assets/js/L.Control.Locate.min.js.map

**Comment by linuxwebexpert** [comment]
Resolved by downloading latest distribution of L.Control.Locate
Note this package also fixes updates to Leaflet 1.1.x+
We subsequently upgraded to latest version - Leaflet 1.2.x

**Comment by marsxul** [comment]
Initial extent can be zoomed in once more

**Comment by marsxul** [comment]
trips planned fail to zoom to the extent of the trip planned and trip chosen

**Comment by marsxul** [comment]
![Screen Shot 09-14-17 at 09.32 AM.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570bcf0e43f5e20e00b09447/125516c66e82c728ace21e0d46db978826878de9bce1b057e40da9d978126a227e44a23f30d5ba66ec103b20224d52be011a001ea9aacd39aca43977db590abfd93b5c70c73b16a9be8a1fbf04bd75834981a4a0980e91b6697abad2c51a7c0c0f0a88f75734a5994ecc58f04ce84e5da217242e.PNG)

**Comment by marsxul** [comment]
![Screen Shot 09-14-17 at 09.33 AM.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/570bcf0e43f5e20e00b09447/125516c66e82c728ace21e0d46db978826878de9bce1b057e40da9d978126a227e44a23f30d5ba66ec113b20224d52be011a001ea9aacd39aca43977db590abfd93b5c70c73b16a9be8a1fbf04bd75834981a4a0980e91b6697abad2c51a7c0c0f0a88f85734a5994ecc58f043e24e55a61a242e.PNG)
