### ISSUE TITLE
Places Search - Messing up with intersections, places

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#140]
Certain places like Diridon or intersections like Santa Clara and Market get geocoded but don't get saved.  If you try to type them in they get geocoded for the trip but get saved as something generic like "San Jose, CA 95110, USA".  If you try to share the url it gives a trip for the center of the zip codes, not the original places typed in.

![screen shot 2017-08-22 at 11 15 50 am](https://user-images.githubusercontent.com/4524205/29580742-e91b3d4a-872b-11e7-9ce1-67ec0b73095a.png)

->

![screen shot 2017-08-22 at 11 15 57 am](https://user-images.githubusercontent.com/4524205/29580750-ec911558-872b-11e7-96c3-8896a51b2c3f.png)

**Comment by 3vivekb** [comment]
This issue extends to data collection.  Only the city / zip is saved, not the original intention.

**Comment by BobVictor** [comment]
**Issue 140: Certain places like Diridon or intersections like Santa Clara and Market get geocoded but don't get saved** is the issue that has been resolved.  Please test/verify, push to PRD when ready and please close this ticket.  another issue has been raised based on CrossStreet Entry order which Google also has.  _Please create a Separate issue for this resolution._ FYI this issue will be extremely time consuming and may not be worth pursuing all things considered.
