### ISSUE TITLE
Investigate source of grey Google Maps

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#147]
Sometimes when using the tripplanner with google maps, the edges are grey.  This affects the printing as well.

Just investigate the source of the problem, see how difficult it is to fix.

![screen shot 2017-11-28 at 11 39 40 am](https://user-images.githubusercontent.com/4524205/33340419-e8ba0032-d430-11e7-8292-ec6648332902.png)

**Comment by bijanmmarkes** [comment]
To fix this issue it would require us to replace google maps API or edit the code within the API itself which we cannot currently do because of the google places terms of service.
