### ISSUE TITLE
Hide Api Keys

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#2]
Don't directly put our google api keys into the code.

**Comment by 3vivekb** [comment]
key in /Users/Vivek/Github/VTA/modeify/client/planner.html
key in modeify/assets/build/manager-app/build.js:

**Comment by Kyle-Falconer** [comment]
also in modeify/assets/build/planner-app/build.js:

**Comment by 3vivekb** [comment]
The solution isn't great.  We need to fix the javascript libraries we use.
