### ISSUE TITLE
Add GPS Button

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#21]
Add a button that let's people put automatically where they are.

**Comment by Kyle-Falconer** [comment]
basic implementation in commit 02f775c16d68d5db79fddb557237454d625ceeee

waiting for verification once https is working on the dev server., because [Chrome disabled geolocation for non-https sites](https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only).

**Comment by 3vivekb** [comment]
Doesn't work when you've put in a previous location.

Steps to reproduce:
1. Get directions from a  given address to another address
2.  Look at directions
3.  x out one of the locations and click the you are here location button

Expected behaviour: Takes new current location and gives you direction

Actual behaviour: Uses previous location

**Comment by 3vivekb** [comment]
Fixed with 85c8f1b10b60e6846ca2a0d47fdd782c4ceef9fd
