### ISSUE TITLE
Trip Descriptions should tell user when the trip starts

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#22]
There should be times mentioned about when Trips start.

**Comment by arichen** [comment]
0:01PM should be 12:01PM

<img width="312" alt="screen shot 2016-08-31 at 7 54 00 pm" src="https://cloud.githubusercontent.com/assets/8155256/18153877/146c121a-6fb5-11e6-9ebd-5ac5e8ed2e4d.png">

**Comment by Kyle-Falconer** [comment]
@arichen fixed in 3293f3985754e971ab8759f23d99e872d6bef79c
