### ISSUE TITLE
Trip Url Bar is broken

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#37]
In www.carfreeatoz.com, if you copy the url and open it, it will open up map directions.  If we generate directions with our trip planner and share the url, it will not open the computed directions.

**Comment by 3vivekb** [comment]
I think if we fix #64 it will fix this issue.

**Comment by Kyle-Falconer** [comment]
remains unfixed, even after #64 is resolved.

**Comment by Kyle-Falconer** [comment]
should now be fixed with f624781a2a35c88d87ad09c140c8109f89ac8e22
