### ISSUE TITLE
Update node version, packages

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#39]
The node version currently being used is v0.12.2.

Maybe we should update the node version and update some of the packages accordingly.

**Comment by 3vivekb** [comment]
We might want to consider dedupe.

The install messages:
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated phantom@0.7.2: v1 is no longer maintained, please upgrade to v2.0+ as soon possible.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated win-spawn@2.0.0: use [cross-spawn](https://github.com/IndigoUnited/node-cross-spawn) or [cross-spawn-async](https://github.com/IndigoUnited/node-cross-spawn-async) instead.
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN deprecated find-file@0.1.4: Use the globby package instead
npm WARN prefer global marked@0.3.6 should be installed with -g
npm WARN prefer global sqwish@0.2.2 should be installed with -g
npm WARN prefer global jshint@2.9.3 should be installed with -g

**Comment by 3vivekb** [comment]
We should also minify our codebase to make it faster.

**Comment by linuxwebexpert** [comment]
Minify of CSS & JS should be a new issue item please as it only occurs on staging / production levels

**Comment by linuxwebexpert** [comment]
We did update all the packages with minimal WARNINGS to latest node & npm - move to close
