### ISSUE TITLE
AC Transit is missing from OTP

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#41]
AC transit directions are missing from trip generation.  So if you try to take a trip within the East Bay, it only suggests BART.

**Comment by marsxul** [comment]
Santa Cruz Metro is also missing,  We need to conduct a full GTFS audit, what are we using and what are we missing.

**Comment by 3vivekb** [comment]
The source of the problem has been identified.  Old GTFS files were not successfully merging with new files.  For now we have deleted the old GTFS files and just grabbed new ones.  AC Transit and Santa Cruz Metro are now working fine.
