### ISSUE TITLE
Android Mobile time gets reset

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#42]
When using tripplanner on Android, you can input the times using the native time changer (good).  The user changes from the default time of whenever they opened the page (good).  And the trip results returned will be appropriate to that time (good).

Unfortunately, you'll still see a blank box after you input a time (bad).  And when you reclick the box the time will be reset to default time, not the changed time you previously requested (bad).

**Comment by 3vivekb** [comment]
Need to figure out all cases where this fails.

**Comment by Kyle-Falconer** [comment]
This is now fixed (unsure when this got fixed).
