### ISSUE TITLE
Time/Distance is covered by "Details" button

### ISSUE THREAD

**Issue by ghost** [vta/modeify#45]
Browser: Google Chrome
Platform: OSX 10.11.6

Steps to Reproduce:
1. Go to https://tripplanner.vta.org/
2. Choose any To/From Destination
3. Click the Search button

Actual Results:
![screen shot 2016-09-22 at 2 36 22 pm](https://cloud.githubusercontent.com/assets/308228/18767109/2edb458e-80d2-11e6-9bf7-2bccfe521fb6.png)

Expected Results:
The time and distance for each selectable route should be visible.

**Comment by 3vivekb** [comment]
This will be handled with #28
