### ISSUE TITLE
Feature Request: Printable routes

### ISSUE THREAD

**Issue by ghost** [vta/modeify#48]
It'd be great to have a print to pdf (or just print) next to the details button for each of the individual routes.

**Comment by marsxul** [comment]
let's prioritize this.

**Comment by 3vivekb** [comment]
- [x] Make print feature only enabled in desktop mode or in ipad mode (if possible) but not in mobile phone mode.
- [x] Add the map to the top of the print screen
- [x] If they don't want to print, and close, out, shouldn't let go of print browser window.
- [x] When testing let's make sure the print function actually works across browsers (VB)

**Comment by 3vivekb** [comment]
Merged to Master
