### ISSUE TITLE
Missing context for arrows in time box

### ISSUE THREAD

**Issue by ghost** [vta/modeify#50]
Browser: Google Chrome
Platform: OSX 10.11.6

Steps to Reproduce:
1. Go to https://tripplanner.vta.org/
2. Click on the clock button next to the Depart/Arrive select box.

Actual Results:
There's a duplicate arrow on the calendar box.

![screen shot 2016-09-22 at 2 57 58 pm](https://cloud.githubusercontent.com/assets/308228/18767619/2cc999e6-80d5-11e6-91ff-4c445c5f963d.png)

Expected Results:
There should be some text that explains that they relate to the "hour" and "minute" dialog. It's odd that you can only go up by the way.

**Comment by 3vivekb** [comment]
Is this from a computer or a phone?

**Comment by ghost** [comment]
It's on OSX; macbook pro

**Comment by ghost** [comment]
Never mind; this isn't a bug, I just didn't scroll down. Could be considered a user error.
