### ISSUE TITLE
"Arrive" toggle doesn't persist

### ISSUE THREAD

**Issue by ghost** [vta/modeify#51]
Browser: Google Chrome
Platform: OSX 10.11.6

Steps to Reproduce:
1. Go to https://tripplanner.vta.org/planner?from=McDonald%27s%2C%201142%20North%20Capitol%20Avenue%2C%20San%20Jose&to=NextSpace%20San%20Jose%2C%2097%20South%20Second%20Street%2C%20San%20Jose&modes=BUSISH%2CTRAINISH%2CWALK&start_time=8&end_time=10&days=M-F&date=09%3A23%3A2016&minute=1
2. Click on "Arrive"
3. Copy and paste the url

Actual Results:
I see the "Depart" toggle selected.

Expected Results:
I'd expect to see the "Arrive" toggle selected.

**Comment by 3vivekb** [comment]
Will be fixed with #66
