### ISSUE TITLE
Create a portable Describe your Trip Bar

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#55]
For integration with the VTA website, we will probably to create a portable Describe your Trip Bar.

![screen shot 2016-10-06 at 11 57 55 am](https://cloud.githubusercontent.com/assets/4524205/19166426/4b1feffc-8bbc-11e6-9c4e-917605fce55d.png)

Do we build the react one?  

Or just update this one to work with our trip planner:
![screen shot 2016-10-06 at 11 59 32 am](https://cloud.githubusercontent.com/assets/4524205/19166448/5eee9042-8bbc-11e6-8d16-499c81a17ff3.png)

**Comment by 3vivekb** [comment]
We need to talk to Patrick Griffen about the VTA.org front page template and see what needs to be done.

**Comment by 3vivekb** [comment]
Blocked by #37.

**Comment by Kyle-Falconer** [comment]
No longer blocked. Ready to be worked on.

Feature requirements:
- have from/to text input fields
- from/to input fields should have address autocomplete
- depart/arrive selector remains
- no date input, defaulting to today's date when the search happens
- have time dropdowns for hours (1-12), minutes (00, 15, 30, 45), and am/pm
- maintain current look and feel of the website, as close as possible

The current search box doesn't work for Stop ID (even though it's shown in the input field), so we should only take in addresses and place names.

The current implementation also doesn't work for Android, and partially works for iOS, so we should be sure to test this on all platforms.

If there is enough time, after completion, add the native date picker for mobile (given the salesforce platform and current website implementation, this significantly increases the complexity of this problem).

**Comment by Kyle-Falconer** [comment]
pending salesforce template/sandbox access

**Comment by 3vivekb** [comment]
Mostly prototyped with:
ecd11d66373b9a2f77f902077adcfd0689bd8b59
@Kyle-Falconer Still needs to improve style.

**Comment by 3vivekb** [comment]
This is completed in this codebase:
https://github.com/vta/salesforce_website
