### ISSUE TITLE
Transit Predictions aren't showing up

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#61]
When you click on the icon that should spit out bus time predictions, it errors out.

![screen shot 2016-10-19 at 9 52 21 am](https://cloud.githubusercontent.com/assets/4524205/19528700/df9f290c-95e1-11e6-8c90-3602f83ee10a.png)

**Comment by marsxul** [comment]
is this a result of the transitime api changes, or need for password?  probably not, since bus data still feeds.

**Comment by 3vivekb** [comment]
I fixed this but I also got to ask what is RTIID? Maybe we should display the stop name instead?  Or some other info?

![screen shot 2016-10-28 at 5 37 53 pm](https://cloud.githubusercontent.com/assets/4524205/19825996/1117c2b8-9d36-11e6-9e61-664e8fc322dc.png)

**Comment by 3vivekb** [comment]
I changed it from RTIID to Stop Id.  It could also become stop code.

![screen shot 2016-10-31 at 10 16 28 am](https://cloud.githubusercontent.com/assets/4524205/19863975/8f31dcdc-9f53-11e6-975f-ba341f08ce88.png)
