### ISSUE TITLE
Fails in iOS 10.0.2 in private mode on Chrome and Safari, private mode in macOS Safari

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#62]
When you try to use the tripplanner in:
macOS Sierra: Safari Private Mode
iPhone: Chrome incognito
iPhone: Safari private mode

The app fails to load a trip.  
![screen shot 2016-10-20 at 2 51 37 pm](https://cloud.githubusercontent.com/assets/4524205/19579400/651e4588-96d5-11e6-80a5-ec5e7d013f6d.png)

It probably has to do with:
[this](http://stackoverflow.com/questions/14555347/html5-localstorage-error-with-safari-quota-exceeded-err-dom-exception-22-an) Thanks @clarle

**Comment by clarle** [comment]
❤️ 📱 🐛

**Comment by clarle** [comment]
FYI this happens with both `localStorage` and `sessionStorage`:

<img width="505" alt="screen shot 2016-10-20 at 3 21 41 pm" src="https://cloud.githubusercontent.com/assets/686352/19580096/fe6203e4-96d8-11e6-989e-7696d74061a7.png">

You'd need to check how `sessionStorage` is accessed in #14 and fallback if `sessionStorage` isn't accessible.

**Comment by 3vivekb** [comment]
We could, as a workaround, just have the site pop up a message and fail when it encounters the incognito browsers.

**Comment by Kyle-Falconer** [comment]
making this "small" to represent the band-aid fix of just notifying the user that we don't support incognito or private mode.
