### ISSUE TITLE
stop highlighting all three routes

### ISSUE THREAD

**Issue by Kyle-Falconer** [vta/modeify#71]
Currently, when a trip is planned, all three routes are shown at once on the map. The RouteCards are sensitive to the mouseenter event to highlight that route on the map, but when the mouseleave event gets fired, all three routes are again shown. This is confusing to the first time user.

Expected behavior is that when a trip is planned, the "best" (first) trip should be highlighted on the map (which is the current mouseenter behavior for that RouteCard). Next, when the user mouses over a different RouteCard, the map should "stick" to that view, even when the mouse is moved away from that RouteCard.

**Comment by linuxwebexpert** [comment]
This issue was resolved in last merge to master -- verifiying

**Comment by linuxwebexpert** [comment]
Now Route Card selection shows all routes on page load and alternates between routes properly, closing issue with Pull 115
