### ISSUE TITLE
upgrading to OTP version 1.0 breaks Modeify

### ISSUE THREAD

**Issue by Kyle-Falconer** [vta/modeify#73]
Some API options have been removed in OpenTripPlanner version 1.0 (see the [changelog](http://docs.opentripplanner.org/en/latest/Changelog/)).

Notably, the "BUSISH" and "TRAINISH" pseudo modes have been removed, so this needs to be updated to "BUS" and "RAIL"

**Comment by 3vivekb** [comment]
Corrected here:
https://github.com/vta/modeify/wiki/OTP-Supervisor-Config
