### ISSUE TITLE
Please confirm bounding box in AmigoCloud is what is used in our OTP

### ISSUE THREAD

**Issue by marsxul** [vta/modeify#92]
https://www.amigocloud.com/dashboard/index.html#/project-dashboard/661/datasets/22492 

I updated the bounding box to include the area we serve, and have GTFS files for.

**Comment by 3vivekb** [comment]
We just hardcoded the bounding box and stopped using the pull from that file.  We felt pulling from that file increased the latency of each places search and also added another http request each time.
