### ISSUE TITLE
Places sometime screw up the geocoding when passing urls

### ISSUE THREAD

**Issue by 3vivekb** [vta/modeify#98]
https://tripplanner.vta.org/planner?from=Gilroy%20Transit%20Center%2C%207250%20Monterey%20Street%2C%20Gilroy%2C%20CA%2095020%2C%20USA&to=San%20Antonio%20%26%20Casey%2C%20United%20States&modes=BICYCLE%2CTRANSIT%2CWALK&days=M-F&arriveBy=true&date=01%3A04%3A2017&hour=5&minute=30&fast=false&safe=true&flat=true

Doesn't work because of the words "Gilroy Transit Center".  But just 7250 Monterey Street, Gilroy CA works.

We might need to check the different types of address components.  Places.  Intersections.  Sometimes It works with the autocomplete, sometimes it doesn't.  We might want to only pass addresses to the url bar.

**Comment by linuxwebexpert** [comment]
This issue has been resolved and verified in Pull 115
Openning a new issue for duplication of place and address on certain locations
You can now type "Gilroy Transit..." and it auto-fills, also "The Home Depot..." works too

**Comment by 3vivekb** [comment]
So we want some key functionality for places with the tripplanner:
1.  If we type in either an address or a place name, google places autocomplete recognizes what it is and that place is geocoded and filled into the box.
2.  You should also be able to generate a url (such as with the vta.org widget) that creates a trip using google places autocomplete that gets geocoded, planned, and displayed for the user.
3.  If you copy the url and put it into a new browser, the same trip and time is geocoded and planned and displayed for the user.

Right now 1. and 2. are working.  But the third option fails.  Maybe it is because of how the url bar is encoded based on the input instructions.

For example, Right now if you input:
From: 3331 N. 1st street, San Jose
To: Gilroy Transit Center
A trip will be computed.  But if you copy the [url](https://devplanner.vta.org/planner?from=3331%20N%201st%20St%2C%20San%20Jose%2C%20CA%2095134%2C%20USA&to=Gilroy%20Transit%20Center%2C%207250%20Monterey%20Street%2C%20Gilroy%2C%20CA%2095020%2C%20USA&modes=TRANSIT%2CWALK&days=M-F&arriveBy=false&date=06%3A14%3A2017&hour=14&minute=43&fast=false&safe=true&flat=true) and paste it into a new browser it fails.  You need to edit the "To" field and remove the place name, and the trip will be computed.

**Comment by linuxwebexpert** [comment]
Fixed in branch geocode_places-#98

Try this link [Devplanner Google Places Test](https://devplanner.vta.org/planner?from=7250%20Monterey%20Rd%2C%20Gilroy%2C%20CA%2095020%2C%20USA&to=Mountain%20View%2C%20CA%2094043%2C%20USA&modes=BICYCLE%2CTRANSIT%2CWALK&days=M-F&arriveBy=true&date=01%3A04%3A2017&hour=5&minute=30&fast=false&safe=true&flat=true) to verify, same link as above reported issue
